# Generated by Django 4.1.7 on 2023-05-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Křestní jméno')),
                ('prijmeni', models.CharField(max_length=100, verbose_name='Křestní jméno')),
                ('email', models.EmailField(max_length=256, verbose_name='E-mail')),
                ('zivotopis', models.CharField(max_length=45, verbose_name='Životopis')),
                ('bio', models.TextField(max_length=2000, verbose_name='Životopis')),
                ('narozeni', models.DateField(verbose_name='Datum narození')),
                ('umrti', models.DateField(verbose_name='Datum umrtí')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autoři',
                'ordering': ['jmeno'],
            },
        ),
    ]
