# Generated by Django 4.1.7 on 2023-05-09 09:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bydliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulice', models.CharField(max_length=30, verbose_name='Název ulice')),
                ('obec', models.CharField(max_length=45, verbose_name='Název obce')),
                ('psc', models.CharField(max_length=7, verbose_name='PSČ')),
            ],
            options={
                'verbose_name': 'Bydliště',
                'verbose_name_plural': 'Bydliště',
                'ordering': ['obec'],
            },
        ),
        migrations.CreateModel(
            name='Nakladatelstvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, verbose_name='Název')),
            ],
            options={
                'verbose_name': 'Nakladatelství',
                'verbose_name_plural': 'Nakladatelství',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Kniha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=17, verbose_name='ISBN knihy')),
                ('titul', models.TextField(max_length=100, verbose_name='Titul knihy')),
                ('strany', models.CharField(max_length=5, verbose_name='Počet stran')),
                ('obsah', models.TextField(max_length=5000, verbose_name='Obsah knihy')),
                ('nakladatelstvi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.nakladatelstvi', verbose_name='Nakladatelství knihy')),
            ],
            options={
                'verbose_name': 'Kniha',
                'verbose_name_plural': 'Knihy',
                'ordering': ['titul'],
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.CharField(max_length=10, verbose_name='Cena')),
                ('isbn', models.CharField(max_length=17, verbose_name='ISBN')),
                ('kniha_isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.kniha', verbose_name='ISBN knihy')),
            ],
            options={
                'verbose_name': 'Exemplář',
                'verbose_name_plural': 'Exempláře',
                'ordering': ['isbn'],
            },
        ),
        migrations.CreateModel(
            name='Ctenar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Křestní jméno')),
                ('prijmeni', models.CharField(max_length=100, verbose_name='Křestní jméno')),
                ('email', models.EmailField(max_length=256, verbose_name='E-mail')),
                ('telefon', models.CharField(help_text='Telefonní číslo', max_length=20, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platné telefonní číslo.', regex='^(\\+420)? ?[1-9][0-9]{2}( ?[0-9]{3}){2}$')], verbose_name='Telefon')),
                ('bydliste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bydliste', verbose_name='Bydliště')),
            ],
            options={
                'verbose_name': 'Čtenář',
                'verbose_name_plural': 'Čtenáři',
                'ordering': ['jmeno'],
            },
        ),
    ]
